# Generated by Django 3.2.9 on 2021-11-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_link', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('example_image', models.CharField(max_length=50)),
                ('pricing', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comment', models.CharField(max_length=300)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmApp.client')),
                ('Good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmApp.good')),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmApp.status')),
            ],
        ),
    ]
