# Generated by Django 3.2.9 on 2021-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_auto_20211117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='example_image',
            field=models.CharField(max_length=300),
        ),
    ]
