# Generated by Django 3.2.9 on 2021-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_alter_good_example_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_link',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
